# Filter parameters selected on the tuning inverter (INV_1700) for each
# disturbance level and applied unchanged to the remaining inverters.

FILTER_PARAMS = {
    "low": {
        "DBSCAN": {"eps": 0.05, "min_samples": 100},
        "IsolationForest": {"contamination": 0.2},
        "LOF": {"n_neighbors": 400, "contamination": 0.4},
        "GMM": {"n_components": 10, "contamination": 0.2},
        "ClearSky_pvlib": {"window_length": 30},
        "L2_ZScore": {"z_crit": 1.3},
        "VarTrimmed_FICP": {"lam": 1.2},
        "Cauchy": {"z_crit": 1.3},
        "GemanMcClure": {"z_crit": 1.3},
        "Welsch": {"z_crit": 1.3},
        "Tukey": {"z_crit": 1.3},
        "Andrew": {"z_crit": 1.3},
        "L1_IRLS": {"z_crit": 1.3},
        "Fair": {"z_crit": 1.3},
        "Logistic": {"z_crit": 1.3},
        "StudentT": {"z_crit": 1.3},
    },
    "medium": {
        "DBSCAN": {"eps": 0.05, "min_samples": 100},
        "IsolationForest": {"contamination": 0.15},
        "LOF": {"n_neighbors": 400, "contamination": 0.5},
        "GMM": {"n_components": 10, "contamination": 0.33},
        "ClearSky_pvlib": {"window_length": 30},
        "L2_ZScore": {"z_crit": 1.4},
        "VarTrimmed_FICP": {"lam": 1.2},
        "Cauchy": {"z_crit": 1.42},
        "GemanMcClure": {"z_crit": 1.42},
        "Welsch": {"z_crit": 1.42},
        "Tukey": {"z_crit": 1.42},
        "Andrew": {"z_crit": 1.42},
        "L1_IRLS": {"z_crit": 1.42},
        "Fair": {"z_crit": 1.42},
        "Logistic": {"z_crit": 1.42},
        "StudentT": {"z_crit": 1.42},
    },
    "high": {
        "DBSCAN": {"eps": 0.055, "min_samples": 90},
        "IsolationForest": {"contamination": 0.25},
        "LOF": {"n_neighbors": 350, "contamination": 0.5},
        "GMM": {"n_components": 10, "contamination": 0.33},
        "ClearSky_pvlib": {"window_length": 30},
        "L2_ZScore": {"z_crit": 0.9},
        "VarTrimmed_FICP": {"lam": 0.5},
        "Cauchy": {"z_crit": 0.9},
        "GemanMcClure": {"z_crit": 0.9},
        "Welsch": {"z_crit": 0.9},
        "Tukey": {"z_crit": 0.9},
        "Andrew": {"z_crit": 0.9},
        "L1_IRLS": {"z_crit": 0.9},
        "Fair": {"z_crit": 0.9},
        "Logistic": {"z_crit": 0.9},
        "StudentT": {"z_crit": 0.9},
    },
}
